config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'home#index'
  resources :artworks
  resources :users
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, :price, :description, :technique, presence: true

  has_many :artwork_attachments, inverse_of: :artwork, dependent: :destroy
  belongs_to :user

  accepts_nested_attributes_for :artwork_attachments, reject_if: :all_blank, allow_destroy: true

  delegate :email, to: :user
end

app/models/artwork_attachment.rb
class ArtworkAttachment < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :artwork
  validates :picture, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :full_address   # can also be an IP address
  after_validation :geocode, if: ->(obj){ obj.city.present? and obj.city_changed? }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_address
    "#{street}, #{zip_code} #{city}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < MarkersController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @artworks = Artwork.all
    super
    fresh_when(@artworks)
  end

  def new
    @artwork = Artwork.new
  end

  def show
    @artwork = Artwork.friendly.find(params[:id])
    super
    fresh_when(@artwork)
  end

  def create
    @artwork = Artwork.new(artwork_params)
    if @artwork.save
      redirect_to artworks_path, notice: 'Votre oeuvre a été ajouté !'
    else
      render :new
    end
  end

  def edit
    @artwork = Artwork.friendly.find(params[:id])
  end

  def update
    @artwork = Artwork.update(artwork_params)
  end

  private

  def artwork_params
     params.require(:artwork).permit(:user_id, :name, :description, :price, :technique, artwork_attachments_attributes: [:id, :picture, :_destroy, :picture_cache])
  end
end

app/controllers/home_controller.rb
class HomeController < MarkersController
  def index
    super
    fresh_when(@users)
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController

  protected

  def index
    @users = User.where.not(latitude: nil, longitude: nil)
    marker_map(@users)
  end

  def show
    @user = Artwork.friendly.find(params[:id]).user
    marker_map(@user)
  end

  private

  def marker_map(marker)
    @markers = Gmaps4rails.build_markers(marker) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end
end

app/controllers/users_controller.rb
class UsersController < MarkersController

  def show
    @user = User.find(params[:id])
    @user_artworks = Artwork.where(user: @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_artwork_attachment_fields.html.erb
<div class="nested-fields">
  <div class="actions-form-artwork">
    <%= f.file_field :picture, class: 'photo_upload file', id: f.object.picture_cache, onchange: "preview(this);" %>
    <%= f.hidden_field :picture_cache, :value => f.object.picture_cache %>
    <%= link_to_remove_association "Supprimer", f %>
  </div>
  <div id="preview"></div>
</div>

app/views/artworks/_card.html.erb
<% @artworks.each do |a| %>
  <div>
    <div class="uk-card uk-card-default uk-card-small">
        <div class="uk-card-media-top">
          <% if a.artwork_attachments.first.present? %>
            <%= link_to artwork_path(a) do %>
              <%=  cl_image_tag a.artwork_attachments.first.picture, height: 250, width: 350, crop: :fill %>
            <% end %>
          <% end %>
        </div>
        <div class="uk-card-body">
          <h3 class="uk-card-title"><%= a.name%></h3>
          <p><%= a.description%></p>
        </div>
    </div>
  </div>
<% end %>

app/views/artworks/_form.html.erb
<%= simple_form_for @artwork do |f| %>
<div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.text_field :name, label: false, placeholder: "Nom de votre oeuvre" %>
  <%= f.text_field :description, label: false, placeholder: "Décrivez-la !" %>
  <%= f.text_field :technique, label: false, placeholder: "Technique utilisée" %>
  <%= f.text_field :price, label: false, placeholder: "Prix/jour" %>
</div>

<div>
  <p><strong>Photo:</strong></p>

    <%= f.simple_fields_for :artwork_attachments do |attachment| %>
      <%= render 'artwork_attachment_fields', f: attachment %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Ajouter une photo', f, :artwork_attachments %>
    </div>
<div>
<%= f.submit %>
<% end %>

app/views/artworks/edit.html.erb
<h3>Editer votre oeuvre</h3>

<%= render 'form' %>

app/views/artworks/index.html.erb
<div class="wrapper">
  <div class="uk-child-width-1-3@l uk-text-center" uk-grid-parallax="translate:200">
    <%= render 'artworks/card' %>
  </div>
</div>

<div id="map" style="width: 50%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function(){
      markers = handler.addMarkers(<%= raw @markers.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  </script>
<% end %>

app/views/artworks/new.html.erb
<h3>Ajouter une nouvelle oeuvre</h3>

<%= render 'form' %>

app/views/artworks/show.html.erb
<h2><%= @artwork.name %></h2>

<ul class="bxslider">
  <% @artwork.artwork_attachments.each do |a| %>
    <%=  cl_image_tag a.picture, :with => 0.25, scale: 1 %>
  <% end %>
</ul>

<% if @user.geocoded? %>
  <div id="show-map" style="width: 50%; height: 600px;"></div>

  <% content_for(:after_js) do %>
    <script type="text/javascript">
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'show-map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(16);
      });
    </script>
  <% end %>
<% end %>


<script>
$(document).ready(function(){
  $('.bxslider').bxSlider();
});
</script>

app/views/home/index.html.erb
<div id="map" style="width: 50%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function(){
      markers = handler.addMarkers(<%= raw @markers.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capfat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <script
      src="https://maps.googleapis.com/maps/api/js?libraries=places&key="#{ENV['GOOGLE_API_BROWSER_KEY']}"">
    </script>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.5/jquery.bxslider.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.5/jquery.bxslider.css">
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= yield(:after_js)%>
  </body>
</html>

app/views/users/show.html.erb
<p><%= @user.email %></p>

<% @user_artworks.each do |artwork| %>
  <%= artwork.name %>
  <%= artwork.artwork_attachments.first.picture %>
<% end %>